server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jira_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SQL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jira.base-url=https://harishragavan973.atlassian.net
jira.username=harishragavan973@gmail.com
jira.api-token=ATATT3xFfGF0_6NSMAvrkxl9mxVLUbqyHNQEMgbq8bFOaiKVORPN3tk3CMlQVLqm0_ZRnJBmji72HZvBzYGYUoVh50UzmzDG77MxOxEDNBb0H94AH2csz0clRV-sHdFSVsM0lc42701uhxECkPyfhexE4CAefDv-MAOvuLyjcirOhL4uo28-kRw=2E4BAD6E

